# Generated by Django 5.2.1 on 2026-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], default='onsite', max_length=20),
        ),
    ]
