# Generated by Django 5.2.1 on 2026-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_experience_required_job_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(max_length=255),
        ),
    ]
