# Generated by Django 5.2.1 on 2026-01-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_add_department_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("onsite", "Onsite"),
                    ("remote", "Remote"),
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
