# Generated by Django 5.2.1 on 2025-10-16 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_department_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='users.department'),
        ),
    ]
