# Generated by Django 5.2.1 on 2025-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_create_course_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
