# Generated by Django 5.2.1 on 2025-12-12 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_created_at_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='year_completed',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
