# Generated by Django 5.2.1 on 2026-01-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_transcript_year_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcript',
            options={'ordering': ['-year_completed', 'degree_level', 'degree']},
        ),
        migrations.AddField(
            model_name='transcript',
            name='degree_level',
            field=models.CharField(blank=True, choices=[("Master's", "Master's"), ('Doctorate', 'Doctorate')], max_length=20, null=True),
        ),
    ]
