# Generated by Django 5.2.1 on 2026-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_transcript_options_transcript_degree_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="work_preference",
            field=models.CharField(max_length=50),
        ),
    ]
