# Generated by Django 5.2.1 on 2026-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_facultyprofile_work_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="work_preference",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
